#!/usr/bin/env bun
// Freezes the load-bearing sections of the six council SKILL.md files into a
// checked-in fixture so `detect-stack.skill-mirror.test.ts` has something to
// assert against in CI, where the operator's `~/.claude/skills` tree does not
// exist.
//
// What the fixture proves and what it does not
// --------------------------------------------
// The fixture is frozen evidence of the contract text. Asserting it against the
// constants exported by `detect-stack.ts` means a rename of a marker name or a
// refusal headline fails CI instead of silently desynchronising the prose that
// the Chair actually obeys. It does NOT prove that any particular machine's
// installed skills still carry that text — only a run against the live tree can,
// and the test keeps that as a second, skip-if-absent case.
//
// Run after editing any council SKILL.md Phase 0 or checkpoint section:
//   bun run scripts/build-council-skill-fixture.ts
//
// Exits non-zero if the skills tree is absent or a required section is missing,
// so "could not extract" never reads as "extracted nothing".

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const SKILLS_ROOT =
  process.env.COUNCIL_SKILLS_ROOT ?? join(homedir(), ".claude", "skills");
const FIXTURE_ROOT = join(
  dirname(new URL(import.meta.url).pathname),
  "__fixtures__",
  "council-skills",
);

const SUFFIXLESS = ["council-plan", "council-implement", "council-review"];
const AURA = SUFFIXLESS.map((s) => `${s}-aura`);

// Section headings to carry into the fixture, by slug family. A suffixless
// skill contributes its Phase 0 router; every skill contributes its checkpoint
// emit phase (the section whose months-long absence from the non-Aura branch
// left every Council observer idle).
const PHASE0 = /^##\s+Phase 0:?\s+Stack [Dd]etection/;
const CHECKPOINT = /^##\s+Phase [\d.]+:\s+Emit Council Checkpoint/;

function extractSection(body: string, heading: RegExp): string | null {
  const lines = body.split("\n");
  const start = lines.findIndex((ln) => heading.test(ln));
  if (start === -1) return null;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].startsWith("## ")) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n").trimEnd();
}

function build(slug: string): string {
  const src = join(SKILLS_ROOT, slug, "SKILL.md");
  if (!existsSync(src)) throw new Error(`SKILL.md not found at ${src}`);
  const body = readFileSync(src, "utf8");

  const wanted: Array<[string, RegExp]> = SUFFIXLESS.includes(slug)
    ? [
        ["Phase 0 stack detection", PHASE0],
        ["checkpoint emit phase", CHECKPOINT],
      ]
    : [["checkpoint emit phase", CHECKPOINT]];

  const parts: string[] = [
    `<!-- GENERATED by scripts/build-council-skill-fixture.ts from ${slug}/SKILL.md — do not edit by hand -->`,
  ];
  for (const [label, heading] of wanted) {
    const section = extractSection(body, heading);
    if (section === null) {
      throw new Error(`${slug}/SKILL.md has no ${label} section`);
    }
    parts.push(section);
  }
  return `${parts.join("\n\n")}\n`;
}

let wrote = 0;
for (const slug of [...SUFFIXLESS, ...AURA]) {
  const out = join(FIXTURE_ROOT, slug, "SKILL.md");
  mkdirSync(dirname(out), { recursive: true });
  const next = build(slug);
  if (!existsSync(out) || readFileSync(out, "utf8") !== next) {
    writeFileSync(out, next, "utf8");
    wrote++;
  }
}
console.log(
  `council skill fixture: ${wrote} written, ${SUFFIXLESS.length + AURA.length - wrote} unchanged`,
);
