#!/usr/bin/env bun
// Freezes the six council SKILL.md dispatchers into a checked-in fixture so
// `skill-dispatcher-contract.test.ts` has something to assert against in CI,
// where the operator's `~/.claude/skills` tree does not exist.
//
// RC-2 note. This used to freeze only the Phase-0 stack-detection router +
// checkpoint sections and pin them against `detect-stack.ts`'s exported marker
// names / refusal headlines. RC-2 retired that two-stack router: selection is
// now adaptive and universal (`selection-engine.md`), and the detector module
// was deleted. The fixture therefore freezes each dispatcher's WHOLE body, and
// this builder fails loud if a body still carries a retired panel/router block
// or is missing the delegation/step tokens the structural contract requires —
// so the fixture can never be regenerated into a non-conforming state, and
// "could not extract" never reads as "extracted nothing".
//
// Run after editing any council SKILL.md:
//   bun run scripts/build-council-skill-fixture.ts

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { findContractViolations } from "./council-skill-contract.js";

const SKILLS_ROOT =
  process.env.COUNCIL_SKILLS_ROOT ?? join(homedir(), ".claude", "skills");
const FIXTURE_ROOT = join(
  dirname(new URL(import.meta.url).pathname),
  "__fixtures__",
  "council-skills",
);

const DISPATCHERS = [
  "council-plan",
  "council-plan-aura",
  "council-review",
  "council-review-aura",
  "council-implement",
  "council-implement-aura",
];

function build(slug: string): string {
  const src = join(SKILLS_ROOT, slug, "SKILL.md");
  if (!existsSync(src)) throw new Error(`SKILL.md not found at ${src}`);
  const body = readFileSync(src, "utf8");

  // Fail loud on the SAME structural contract skill-dispatcher-contract.test.ts
  // enforces (one shared source — council-skill-contract.ts), so the fixture can
  // never be frozen into a non-conforming state.
  const violations = findContractViolations(body);
  if (violations.length > 0) {
    throw new Error(`${slug}/SKILL.md fails the dispatcher contract; cannot freeze:\n  ${violations.join("\n  ")}`);
  }

  return (
    `<!-- GENERATED by scripts/build-council-skill-fixture.ts from ${slug}/SKILL.md — do not edit by hand -->\n` +
    body
  );
}

let wrote = 0;
for (const slug of DISPATCHERS) {
  const out = join(FIXTURE_ROOT, slug, "SKILL.md");
  mkdirSync(dirname(out), { recursive: true });
  const next = build(slug);
  if (!existsSync(out) || readFileSync(out, "utf8") !== next) {
    writeFileSync(out, next, "utf8");
    wrote++;
  }
}
console.log(
  `council skill fixture: ${wrote} written, ${DISPATCHERS.length - wrote} unchanged`,
);
