// Structural contract for the six council SKILL.md dispatchers (RC-2).
// (Was detect-stack.skill-mirror.test.ts — renamed, fowler #3: it no longer mirrors
// the deleted detect-stack.ts; it enforces the post-consolidation dispatcher shape.)
//
// The property the migration must not silently regress: no dispatcher embeds a fixed
// panel or the retired two-stack stack-detection router; all six delegate selection
// to selection-engine.md; all six carry the council/checkpoint emit step.
//
// The check is STRUCTURAL, not a stale substring blocklist (beck #1): alongside the
// retired-marker substrings it forbids the fixed-panel SHAPE (a run of bare
// advisor-id bullets), so a panel re-embedded under a renamed heading — the exact
// evasion the previous version missed — is still caught. The contract lives in one
// shared module (council-skill-contract.ts) imported by both this test and the
// fixture builder, so the two cannot drift (fowler #4).
//
// Two roots: a checked-in fixture (never skipped — the CI-hermetic tripwire for a
// hand-edited fixture) and the operator's live ~/.claude/skills (skipped when absent).
//
// CIRCULARITY NOTE (beck #2): the fixture is generated by build-council-skill-fixture.ts
// under the SAME contract this test asserts, so the fixture arm proves self-consistency,
// not that a LIVE SKILL.md still conforms. The authoritative gate for the live skills is
// the catalog repo's verify-catalog.sh + its CI (C1/C2/C6/C11/C12). The live arm below is
// the local half of that; run `bun run scripts/build-council-skill-fixture.ts` after any
// live SKILL.md edit (it fails loud on a violation) to keep the frozen fixture honest.

import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import { findContractViolations, REQUIRED_TOKENS } from "./council-skill-contract.js";

const FIXTURE_ROOT = join(dirname(new URL(import.meta.url).pathname), "__fixtures__", "council-skills");
const LIVE_ROOT = process.env.COUNCIL_SKILLS_ROOT ?? join(homedir(), ".claude", "skills");

const DISPATCHERS = [
  "council-plan",
  "council-plan-aura",
  "council-review",
  "council-review-aura",
  "council-implement",
  "council-implement-aura",
];

function runSuite(rootLabel: string, root: string) {
  function skillBody(slug: string): string {
    const path = join(root, slug, "SKILL.md");
    if (!existsSync(path)) throw new Error(`SKILL.md not found at ${path}`);
    return readFileSync(path, "utf8");
  }

  describe(`SKILL.md structural contract (${rootLabel})`, () => {
    describe.each(DISPATCHERS)("%s", (slug) => {
      it("embeds no fixed panel and no stack-detection router, and delegates to the engine", () => {
        const violations = findContractViolations(skillBody(slug));
        expect(violations, `${slug}/SKILL.md contract violations:\n  ${violations.join("\n  ")}`).toEqual([]);
      });
    });
  });
}

// Prove the structural check actually BITES — a stale substring blocklist would not
// catch a panel under a renamed heading (the beck #1 evasion). This asserts the
// contract fails on the panel SHAPE regardless of the heading text.
describe("findContractViolations — catches a re-embedded panel under a renamed heading (beck #1)", () => {
  it("flags a bare-advisor-id bullet run even under an innocuous new heading", () => {
    const evasion = [
      "## Phase 0: Advisor Selection",
      "reference the engine, sure, but then:",
      "## The real roster",
      "- hunt",
      "- fowler",
      "- dahl",
      "council/checkpoint selection-engine.md",
    ].join("\n");
    const v = findContractViolations(evasion);
    expect(v.some((x) => x.includes("fixed-panel bullet run"))).toBe(true);
  });
  it("passes a conforming delegating body", () => {
    const ok = [
      "## Phase 0: Advisor Selection",
      "Selection is delegated to selection-engine.md; the catalog is the panel.",
      "Emit the council/checkpoint after planning.",
    ].join("\n");
    expect(findContractViolations(ok)).toEqual([]);
  });
  it("flags a missing required delegation token", () => {
    expect(findContractViolations("no tokens here").some((x) => x.includes("selection-engine.md"))).toBe(true);
    expect(REQUIRED_TOKENS).toContain("council/checkpoint");
  });
});

// Never skipped — CI-hermetic tripwire for a hand-edited fixture.
runSuite("checked-in fixture", FIXTURE_ROOT);

// The operator's actual installation. Absent in bare CI.
const liveRootExists = existsSync(LIVE_ROOT);
describe.skipIf(!liveRootExists)("live skills tree", () => {
  runSuite("live tree", LIVE_ROOT);
});
